# ============================================================
# Logging
# ============================================================

# Log levels
# DEBUG, INFO, WARNING, ERROR, CRITICAL
[logging.console]
enabled = true
# Can be overridden with:
#   --loglevel LEVEL
#   --debug all
level = "DEBUG"

# Can be overridden with:
#   --debug dependencies
#   --debug all
dependency_level = "WARNING"

[logging.file]
enabled = true               # currently not possible to disable
level = "DEBUG"
dependency_level = "WARNING"
rotation = "midnight"        # D: Daily, H: Hourly, M: every minute, S: every second, midnight: at midnight
retain_days = 14             # for how many days the logs should be kept
utc_time = false             # true: UTC time, false: local time
