[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "prompt"
version = "1.0"
requires-python = ">=3.14"

dependencies = [
    "platformdirs>=4.11.3",
    "prompt-toolkit>=3.0.53",
    "pydantic>=2.13.4",
    "pyperclip>=1.11.0",
]


[project.scripts]
prompt = "prompt_manager.main:main"

[tool.setuptools.packages.find]
where = ["src"]
[tool.setuptools.package-data]
prompt_manager = ["defaults/*"]

[dependency-groups]
dev = ["debugpy>=1.8.20", "pytest>=9.0.3"]
